# Generated by Django 5.1.2 on 2024-10-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='storage',
            new_name='RAM',
        ),
    ]
