# Generated by Django 5.1.2 on 2024-11-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_storage_mobile_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_images'),
        ),
    ]
